CREATE TABLE IF NOT EXISTS userbook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES app_user(id),
    book_id BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (book_id) REFERENCES book(id),
    created_at TIMESTAMP,
    modified_at TIMESTAMP
);
