vars:
    db:
        host: localhost
        name: openbook
        user: leafnote
        pass: leafnote

logging:
    level:
        root: debug

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  prometheus:
    metrics:
      export:
        enabled: true

spring:
    application:
        name: openbook
    datasource:
        url: jdbc:postgresql://${vars.db.host}:5432/${vars.db.name}?sslmode=disable
        username: ${vars.db.user}
        password: ${vars.db.pass}
    jackson:
        default-property-inclusion: non_null
    jpa:
        properties:
            hibernate:
                connection:
                    url: jdbc:postgresql://${vars.db.host}:5432/${vars.db.name}?sslmode=disable
                    username: ${vars.db.user}
                    password: ${vars.db.pass}
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: validate
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        show-sql: false

springdoc:
    swagger-ui:
        path: /api-docs.html
        syntaxHighlight:
            theme: light

# disable flyway execution
#spring.flyway.enabled=false

# If you have an existing database and start using Flyway for new database changes.
#spring.flyway.baseline-on-migrate=true

# To customize flyway migrations tracking table name
#spring.flyway.table=db_migrations

# In case of any flyway execution errors, clean up the database and re-run all the migrations
## NEVER USE THIS IN PRODUCTION. ONLY SUITABLE FOR PROTOTYPING
#spring.flyway.clean-disabled=false
#spring.flyway.clean-on-validation-error=true
